<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Auth;
use Tests\TestCase;

class RoleTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Auth::login(User::first());
    }

    public function test_cant_view_roles_page_if_not_logged_in()
    {
        Auth::logout();
        $response = $this->get('/roles');
        $response->assertStatus(302);
    }


    public function test_logged_in_user_can_view_roles_page()
    {
        $response = $this->get('/roles');
        $response->assertStatus(200);
    }


    public function test_can_create_new_role(){
        //$this->withoutExceptionHandling();

        $response = $this->post('/roles',[
            'name' => 'test role',
            'guard_name' => 'web'
        ]);

        $response->assertRedirect('roles');
    }
}
